### ISSUE TITLE
Use flag for parameters

### ISSUE THREAD

**Issue by paddie** [AnirudhBhat/subdb.go#4]
Use the [flag](http://golang.org/pkg/flag/) package to parse the files; It allows you to provide named parameters, and a help menu (which is really nice in this case, since you don't actually provide an example of how the language is formatted).

And finally, in the url-string you use ",en", where you should really only use "en":
This:

``` Go
url := "http://api.thesubdb.com/?action=download&hash=" + hash + "&language=" + language + ",en"
```

Should be:

``` Go
url := "http://api.thesubdb.com/?action=download&hash=" + hash + "&language=" + language + "en"

```
# Code for using flag:

``` Go
var (
    filepath string
    language string
)

func init() {
    flag.StringVar(&filepath, "f", "", "Path to the movie file")
    flag.StringVar(&language, "l", "en", "The required language of the subtitles")
}

func main() {
        flag.Parse()

    if filepath == "" {
        fmt.Println("Provide path to movie file etc.")
        os.Exit(1)
    }

        // Validate that language is of length == 2 etc.
}
```
# Example usage:

```
subdb -f movie.mp4
subdb -f movie.mp4 -l it
```

**Comment by AnirudhBhat** [comment]
Thanks paddie, i have used flags now for better command line arguments parsing.
